Update lib.rs because of change in nightly
Building with latest rust nightlies are throwing this error.
```
error: legacy asm! syntax is no longer supported
   --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/subtle-2.2.2/src/lib.rs:150:14
    |
150 |     unsafe { asm!("" : "=r"(input) : "0"(input) ) }
    |              ----^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |              |
    |              help: replace with: `llvm_asm!
```
So I did the change.  ¯\_(ツ)_/¯